matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/combinatorics.git
  - cd combinatorics
  - git checkout -b develop origin/develop
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/my_cuda.git
  - git clone https://github.com/quicky2000/parameter_manager.git
  - git clone https://github.com/quicky2000/quicky_exception.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build; cd build; generate_makefile CUDA_eternity2 ; make test enable_cuda=0; fi
  - cd $MY_LOCATION ; mkdir cmake_build ; cd cmake_build ; cmake $QUICKY_REPOSITORY/CUDA_eternity2
  - make
#EOF
